name: makeitnative
favicon: null
layout_spectrum: 0.6008462528698146
typography_spectrum: 0.331657211529091
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.8108441606163979
  lightness: 0.4786068769171834
  saturation: 0.23537372425198555
  rhythmicContrast: 0.7954567596316338
purpose: []
